-- Run this once in Supabase SQL Editor.
-- It powers anonymous per-photo likes on /masonry/.

create table if not exists public.gallery_likes (
  id bigint generated by default as identity primary key,
  image_key text not null check (char_length(image_key) between 1 and 500),
  visit_id text not null check (char_length(visit_id) between 8 and 120),
  created_at timestamptz not null default now()
);

create index if not exists gallery_likes_image_key_created_at_idx
  on public.gallery_likes (image_key, created_at desc);

alter table public.gallery_likes enable row level security;

drop policy if exists "Anyone can read gallery likes" on public.gallery_likes;
create policy "Anyone can read gallery likes"
  on public.gallery_likes
  for select
  using (true);

drop policy if exists "Anyone can create gallery likes" on public.gallery_likes;
create policy "Anyone can create gallery likes"
  on public.gallery_likes
  for insert
  with check (char_length(image_key) between 1 and 500 and char_length(visit_id) between 8 and 120);

grant select, insert on table public.gallery_likes to anon, authenticated;
grant usage, select on sequence public.gallery_likes_id_seq to anon, authenticated;
