-- Run this once in Supabase SQL Editor.
-- It creates the table used by js/blog-interactions.js for GitHub-authenticated comments.

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_path text not null,
  post_title text not null,
  body text not null check (char_length(body) between 1 and 1000),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  user_avatar text,
  created_at timestamptz not null default now()
);

create index if not exists post_comments_post_path_created_at_idx
  on public.post_comments (post_path, created_at);

alter table public.post_comments enable row level security;

drop policy if exists "Anyone can read blog comments" on public.post_comments;
create policy "Anyone can read blog comments"
  on public.post_comments
  for select
  using (true);

drop policy if exists "Signed-in users can create own comments" on public.post_comments;
create policy "Signed-in users can create own comments"
  on public.post_comments
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own comments" on public.post_comments;
create policy "Users can delete own comments"
  on public.post_comments
  for delete
  to authenticated
  using (auth.uid() = user_id);
