-- Run this once in Supabase SQL Editor.
-- It powers the HOME sidebar Likes counter.

create table if not exists public.site_likes (
  id bigint generated by default as identity primary key,
  site_key text not null default 'home',
  client_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists site_likes_site_key_created_at_idx
  on public.site_likes (site_key, created_at desc);

alter table public.site_likes enable row level security;

drop policy if exists "Anyone can read site likes" on public.site_likes;
create policy "Anyone can read site likes"
  on public.site_likes
  for select
  using (true);

drop policy if exists "Anyone can create site likes" on public.site_likes;
create policy "Anyone can create site likes"
  on public.site_likes
  for insert
  with check (site_key = 'home' and char_length(client_id) between 8 and 120);
grant select, insert on table public.site_likes to anon, authenticated;
grant usage, select on sequence public.site_likes_id_seq to anon, authenticated;