-- Run this once in Supabase SQL Editor.
-- It powers the HOME guestbook, /comments/ history page, replies, and likes.

create table if not exists public.site_comments (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.site_comments(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 800),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_name text not null,
  user_avatar text,
  created_at timestamptz not null default now()
);

create index if not exists site_comments_parent_created_at_idx
  on public.site_comments (parent_id, created_at);

create index if not exists site_comments_created_at_idx
  on public.site_comments (created_at desc);

alter table public.site_comments enable row level security;

drop policy if exists "Anyone can read site comments" on public.site_comments;
create policy "Anyone can read site comments"
  on public.site_comments
  for select
  using (true);

drop policy if exists "Signed-in users can create site comments" on public.site_comments;
create policy "Signed-in users can create site comments"
  on public.site_comments
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own site comments" on public.site_comments;
create policy "Users can delete own site comments"
  on public.site_comments
  for delete
  to authenticated
  using (auth.uid() = user_id);

create table if not exists public.site_comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.site_comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create index if not exists site_comment_likes_comment_id_idx
  on public.site_comment_likes (comment_id);

alter table public.site_comment_likes enable row level security;

drop policy if exists "Anyone can read site comment likes" on public.site_comment_likes;
create policy "Anyone can read site comment likes"
  on public.site_comment_likes
  for select
  using (true);

drop policy if exists "Signed-in users can like site comments" on public.site_comment_likes;
create policy "Signed-in users can like site comments"
  on public.site_comment_likes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can unlike own site comment likes" on public.site_comment_likes;
create policy "Users can unlike own site comment likes"
  on public.site_comment_likes
  for delete
  to authenticated
  using (auth.uid() = user_id);
