-- Run this once in Supabase SQL Editor.
-- It stores anonymous visit analytics sent through the track-visit Edge Function.
-- The frontend never writes to this table directly; the Edge Function uses the service role key.

create table if not exists public.visit_analytics (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null default 'page_view' check (event_type in ('page_view', 'gallery_load')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 120),
  session_id text check (session_id is null or char_length(session_id) between 8 and 120),
  page_path text not null default '/',
  page_url text,
  referrer text,
  ip_hash text,
  country text,
  region text,
  city text,
  device_type text not null default 'unknown' check (device_type in ('desktop', 'mobile', 'tablet', 'unknown')),
  os_name text,
  os_version text,
  browser_name text,
  browser_version text,
  user_agent text,
  language text,
  timezone text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  pixel_ratio numeric,
  gallery_load_ms integer,
  gallery_image_total integer,
  gallery_image_loaded integer,
  gallery_image_failed integer,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists visit_analytics_created_at_idx
  on public.visit_analytics (created_at desc);

create index if not exists visit_analytics_event_created_at_idx
  on public.visit_analytics (event_type, created_at desc);

create index if not exists visit_analytics_visitor_created_at_idx
  on public.visit_analytics (visitor_id, created_at desc);

create index if not exists visit_analytics_page_created_at_idx
  on public.visit_analytics (page_path, created_at desc);

create index if not exists visit_analytics_ip_hash_created_at_idx
  on public.visit_analytics (ip_hash, created_at desc);

alter table public.visit_analytics enable row level security;

-- No anon/authenticated insert policy is created on purpose.
-- Inserts should go through the Edge Function with SUPABASE_SERVICE_ROLE_KEY.

create or replace view public.visit_analytics_daily_summary as
select
  date_trunc('day', created_at) as day,
  count(*) filter (where event_type = 'page_view') as page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view') as unique_visitors,
  count(*) filter (where event_type = 'gallery_load') as gallery_load_events,
  avg(gallery_load_ms) filter (where event_type = 'gallery_load') as avg_gallery_load_ms
from public.visit_analytics
group by 1
order by 1 desc;