-- Run this once in Supabase SQL Editor.
-- It stores anonymous visit analytics sent through the track-visit Edge Function.
-- The frontend never writes to this table directly; the Edge Function uses the service role key.

create table if not exists public.visit_analytics (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null default 'page_view' check (event_type in ('page_view', 'gallery_load')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 120),
  session_id text check (session_id is null or char_length(session_id) between 8 and 120),
  page_path text not null default '/',
  page_url text,
  referrer text,
  ip_hash text,
  country text,
  region text,
  city text,
  device_type text not null default 'unknown' check (device_type in ('desktop', 'mobile', 'tablet', 'unknown')),
  os_name text,
  os_version text,
  browser_name text,
  browser_version text,
  user_agent text,
  language text,
  timezone text,
  screen_width integer,
  screen_height integer,
  viewport_width integer,
  viewport_height integer,
  pixel_ratio numeric,
  gallery_load_ms integer,
  gallery_image_total integer,
  gallery_image_loaded integer,
  gallery_image_failed integer,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists visit_analytics_created_at_idx
  on public.visit_analytics (created_at desc);

create index if not exists visit_analytics_event_created_at_idx
  on public.visit_analytics (event_type, created_at desc);

create index if not exists visit_analytics_visitor_created_at_idx
  on public.visit_analytics (visitor_id, created_at desc);

create index if not exists visit_analytics_page_created_at_idx
  on public.visit_analytics (page_path, created_at desc);

create index if not exists visit_analytics_ip_hash_created_at_idx
  on public.visit_analytics (ip_hash, created_at desc);

alter table public.visit_analytics enable row level security;

-- No anon/authenticated insert policy is created on purpose.
-- Inserts should go through the Edge Function with SUPABASE_SERVICE_ROLE_KEY.

create table if not exists public.visit_ip_geo_cache (
  ip_hash text primary key,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  country text,
  region text,
  city text,
  country_code text,
  geo_provider text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists visit_ip_geo_cache_last_seen_at_idx
  on public.visit_ip_geo_cache (last_seen_at desc);

create index if not exists visit_ip_geo_cache_country_city_idx
  on public.visit_ip_geo_cache (country, city);

alter table public.visit_ip_geo_cache enable row level security;

-- No anon/authenticated policy is created on purpose.
-- This table is written only by the Edge Function service role and stores no raw IP addresses.

create table if not exists public.bot_visit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null default 'page_view' check (event_type in ('page_view', 'gallery_load')),
  page_path text not null default '/',
  page_url text,
  referrer text,
  ip_hash text,
  bot_name text not null,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists bot_visit_logs_created_at_idx
  on public.bot_visit_logs (created_at desc);

create index if not exists bot_visit_logs_bot_created_at_idx
  on public.bot_visit_logs (bot_name, created_at desc);

alter table public.bot_visit_logs enable row level security;

-- No anon/authenticated policy is created on purpose.
-- Bot logs are written only by the Edge Function service role and are not included in visitor rollups.

create table if not exists public.visitor_easter_egg_discoveries (
  id bigint generated by default as identity primary key,
  visitor_id text not null unique check (char_length(visitor_id) between 8 and 120),
  discovered_at timestamptz not null default now()
);

create index if not exists visitor_easter_egg_discoveries_discovered_at_idx
  on public.visitor_easter_egg_discoveries (discovered_at desc);

alter table public.visitor_easter_egg_discoveries enable row level security;

-- No anon/authenticated policy is created on purpose.
-- Discovery writes go through the track-visit Edge Function with the service role key.

create or replace function public.register_easter_egg_discovery(p_visitor_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_visitor_id text;
  discovery_row public.visitor_easter_egg_discoveries%rowtype;
  discovery_rank bigint;
  discovery_total bigint;
begin
  normalized_visitor_id := nullif(trim(p_visitor_id), '');

  if normalized_visitor_id is null
    or char_length(normalized_visitor_id) < 8
    or char_length(normalized_visitor_id) > 120 then
    raise exception 'visitor_id is required';
  end if;

  insert into public.visitor_easter_egg_discoveries (visitor_id)
  values (normalized_visitor_id)
  on conflict (visitor_id) do nothing;

  select *
  into discovery_row
  from public.visitor_easter_egg_discoveries
  where visitor_id = normalized_visitor_id;

  select count(*)
  into discovery_rank
  from public.visitor_easter_egg_discoveries
  where id <= discovery_row.id;

  select count(*)
  into discovery_total
  from public.visitor_easter_egg_discoveries;

  return jsonb_build_object(
    'discovery_rank', discovery_rank,
    'easter_egg_unique_visitors', discovery_total,
    'discovered_at', discovery_row.discovered_at
  );
end;
$$;

grant execute on function public.register_easter_egg_discovery(text) to service_role;
create or replace view public.visit_analytics_daily_summary as
select
  date_trunc('day', created_at) as day,
  count(*) filter (where event_type = 'page_view') as page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view') as unique_visitors,
  count(*) filter (where event_type = 'gallery_load') as gallery_load_events,
  avg(gallery_load_ms) filter (where event_type = 'gallery_load') as avg_gallery_load_ms
from public.visit_analytics
group by 1
order by 1 desc;
-- Pre-aggregated visitor analytics for the public easter-egg statistics page.
-- This keeps /analytics/ fast: the frontend can read one small row instead of scanning raw visits.
create table if not exists public.visit_analytics_rollup (
  id boolean primary key default true check (id),
  updated_at timestamptz not null default now(),
  total_page_views bigint not null default 0,
  unique_visitors bigint not null default 0,
  gallery_load_events bigint not null default 0,
  avg_gallery_load_ms numeric,
  regions jsonb not null default '[]'::jsonb,
  countries jsonb not null default '[]'::jsonb,
  cities jsonb not null default '[]'::jsonb,
  devices jsonb not null default '[]'::jsonb,
  systems jsonb not null default '[]'::jsonb,
  browsers jsonb not null default '[]'::jsonb
);

alter table public.visit_analytics_rollup
  add column if not exists bots jsonb not null default '[]'::jsonb;

alter table public.visit_analytics_rollup enable row level security;

drop policy if exists "Anyone can read visit analytics rollup" on public.visit_analytics_rollup;
create policy "Anyone can read visit analytics rollup"
  on public.visit_analytics_rollup
  for select
  using (true);

create or replace function public.refresh_visit_analytics_rollup()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  with page_views as (
    select
      *,
      case
        when country is null or btrim(country) = '' or lower(btrim(country)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
        else btrim(country)
      end as clean_country,
      case
        when region is null or btrim(region) = '' or lower(btrim(region)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
        else btrim(region)
      end as clean_region,
      case
        when city is null or btrim(city) = '' or lower(btrim(city)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
        else btrim(city)
      end as clean_city
    from public.visit_analytics
    where event_type = 'page_view'
  ),
  gallery_loads as (
    select *
    from public.visit_analytics
    where event_type = 'gallery_load'
  ),
  visitor_regions as (
    select distinct on (visitor_id)
      visitor_id,
      clean_country,
      clean_region,
      clean_city
    from page_views
    order by
      visitor_id,
      case when clean_country is not null or clean_region is not null or clean_city is not null then 0 else 1 end,
      created_at desc
  ),
  region_summary as (
    select
      coalesce(
        clean_country || case when clean_city is not null then ' / ' || clean_city else case when clean_region is not null then ' / ' || clean_region else '' end end,
        clean_region || case when clean_city is not null and clean_city <> clean_region then ' / ' || clean_city else '' end,
        clean_city,
        'Unknown'
      ) as label,
      count(*) as total
    from visitor_regions
    group by 1
    order by total desc, label asc
  ),
  country_summary as (
    select coalesce(clean_country, 'Unknown') as label, count(distinct visitor_id) as total
    from page_views
    group by 1
    order by total desc, label asc
    limit 12
  ),
  city_summary as (
    select coalesce(clean_city, 'Unknown') as label, count(distinct visitor_id) as total
    from page_views
    group by 1
    order by total desc, label asc
    limit 12
  ),
  device_summary as (
    select coalesce(nullif(device_type, ''), 'unknown') as label, count(distinct visitor_id) as total
    from page_views
    group by 1
    order by total desc, label asc
  ),
  os_summary as (
    select coalesce(nullif(os_name, ''), 'Unknown') as label, count(distinct visitor_id) as total
    from page_views
    group by 1
    order by total desc, label asc
    limit 10
  ),
  browser_summary as (
    select coalesce(nullif(browser_name, ''), 'not claim') as label, count(distinct visitor_id) as total
    from page_views
    group by 1
    order by total desc, label asc
    limit 10
  ),
  bot_summary as (
    select coalesce(nullif(bot_name, ''), 'Unknown Bot') as label, count(*) as total
    from public.bot_visit_logs
    group by 1
    order by total desc, label asc
    limit 10
  ),
  payload as (
    select
      true as id,
      now() as updated_at,
      (select count(*) from page_views)::bigint as total_page_views,
      (select count(distinct visitor_id) from page_views)::bigint as unique_visitors,
      (select count(*) from gallery_loads)::bigint as gallery_load_events,
      (select avg(gallery_load_ms) from gallery_loads where gallery_load_ms is not null) as avg_gallery_load_ms,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from region_summary), '[]'::jsonb) as regions,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from country_summary), '[]'::jsonb) as countries,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from city_summary), '[]'::jsonb) as cities,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from device_summary), '[]'::jsonb) as devices,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from os_summary), '[]'::jsonb) as systems,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from browser_summary), '[]'::jsonb) as browsers,
      coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from bot_summary), '[]'::jsonb) as bots
  ),
  upserted as (
    insert into public.visit_analytics_rollup (
      id,
      updated_at,
      total_page_views,
      unique_visitors,
      gallery_load_events,
      avg_gallery_load_ms,
      regions,
      countries,
      cities,
      devices,
      systems,
      browsers,
      bots
    )
    select
      id,
      updated_at,
      total_page_views,
      unique_visitors,
      gallery_load_events,
      avg_gallery_load_ms,
      regions,
      countries,
      cities,
      devices,
      systems,
      browsers,
      bots
    from payload
    on conflict (id) do update set
      updated_at = excluded.updated_at,
      total_page_views = excluded.total_page_views,
      unique_visitors = excluded.unique_visitors,
      gallery_load_events = excluded.gallery_load_events,
      avg_gallery_load_ms = excluded.avg_gallery_load_ms,
      regions = excluded.regions,
      countries = excluded.countries,
      cities = excluded.cities,
      devices = excluded.devices,
      systems = excluded.systems,
      browsers = excluded.browsers,
      bots = excluded.bots
    returning *
  )
  select jsonb_build_object(
    'total_page_views', total_page_views,
    'unique_visitors', unique_visitors,
    'gallery_load_events', gallery_load_events,
    'avg_gallery_load_ms', avg_gallery_load_ms,
    'regions', regions,
    'countries', countries,
    'cities', cities,
    'devices', devices,
    'systems', systems,
    'browsers', browsers,
    'bots', bots,
    'easter_egg_unique_visitors', (select count(*) from public.visitor_easter_egg_discoveries),
    'generated_at', updated_at
  )
  into result
  from upserted;

  return result;
end;
$$;

grant execute on function public.refresh_visit_analytics_rollup() to service_role;

create or replace function public.get_visit_analytics_rollup(p_visitor_id text default null)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with visitor_location as (
  select country, region, city
  from public.visit_analytics
  where event_type = 'page_view'
    and visitor_id = p_visitor_id
    and (country is not null or region is not null or city is not null)
  order by created_at desc
  limit 1
),
rollup as (
  select *
  from public.visit_analytics_rollup
  where id = true
)
select jsonb_build_object(
  'total_page_views', coalesce((select total_page_views from rollup), 0),
  'unique_visitors', coalesce((select unique_visitors from rollup), 0),
  'gallery_load_events', coalesce((select gallery_load_events from rollup), 0),
  'avg_gallery_load_ms', (select avg_gallery_load_ms from rollup),
  'visitor_location', coalesce((select jsonb_build_object('country', country, 'region', region, 'city', city) from visitor_location), '{}'::jsonb),
  'regions', coalesce((select regions from rollup), '[]'::jsonb),
  'countries', coalesce((select countries from rollup), '[]'::jsonb),
  'cities', coalesce((select cities from rollup), '[]'::jsonb),
  'devices', coalesce((select devices from rollup), '[]'::jsonb),
  'systems', coalesce((select systems from rollup), '[]'::jsonb),
  'browsers', coalesce((select browsers from rollup), '[]'::jsonb),
  'bots', coalesce((select bots from rollup), '[]'::jsonb),
  'easter_egg_unique_visitors', (select count(*) from public.visitor_easter_egg_discoveries),
  'generated_at', (select updated_at from rollup)
);
$$;

-- Keep the existing frontend RPC name fast without requiring an immediate frontend change.
-- If the rollup has not been generated yet, it falls back to the original live aggregation.
create or replace function public.get_visit_analytics_summary(p_visitor_id text default null)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with rollup_exists as (
  select exists(select 1 from public.visit_analytics_rollup where id = true) as has_rollup
),
rollup_payload as (
  select public.get_visit_analytics_rollup(p_visitor_id) as payload
  where (select has_rollup from rollup_exists)
),
page_views as (
  select
    *,
    case
      when country is null or btrim(country) = '' or lower(btrim(country)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
      else btrim(country)
    end as clean_country,
    case
      when region is null or btrim(region) = '' or lower(btrim(region)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
      else btrim(region)
    end as clean_region,
    case
      when city is null or btrim(city) = '' or lower(btrim(city)) in ('unknown', 'n/a', 'na', 'null', 'undefined') then null
      else btrim(city)
    end as clean_city
  from public.visit_analytics
  where event_type = 'page_view'
    and not (select has_rollup from rollup_exists)
),
visitor_location as (
  select country, region, city
  from page_views
  where visitor_id = p_visitor_id
    and (country is not null or region is not null or city is not null)
  order by created_at desc
  limit 1
),
visitor_regions as (
  select distinct on (visitor_id)
    visitor_id,
    clean_country,
    clean_region,
    clean_city
  from page_views
  order by
    visitor_id,
    case when clean_country is not null or clean_region is not null or clean_city is not null then 0 else 1 end,
    created_at desc
),
region_summary as (
  select
    coalesce(
      clean_country || case when clean_city is not null then ' / ' || clean_city else case when clean_region is not null then ' / ' || clean_region else '' end end,
      clean_region || case when clean_city is not null and clean_city <> clean_region then ' / ' || clean_city else '' end,
      clean_city,
      'Unknown'
    ) as label,
    count(*) as total
  from visitor_regions
  group by 1
  order by total desc, label asc
),
device_summary as (
  select coalesce(nullif(device_type, ''), 'unknown') as label, count(distinct visitor_id) as total
  from page_views
  group by 1
  order by total desc, label asc
),
os_summary as (
  select coalesce(nullif(os_name, ''), 'Unknown') as label, count(distinct visitor_id) as total
  from page_views
  group by 1
  order by total desc, label asc
  limit 10
),
browser_summary as (
  select coalesce(nullif(browser_name, ''), 'not claim') as label, count(distinct visitor_id) as total
  from page_views
  group by 1
  order by total desc, label asc
  limit 10
),
bot_summary as (
  select coalesce(nullif(bot_name, ''), 'Unknown Bot') as label, count(*) as total
  from public.bot_visit_logs
  group by 1
  order by total desc, label asc
  limit 10
),
live_payload as (
  select jsonb_build_object(
    'total_page_views', (select count(*) from page_views),
    'unique_visitors', (select count(distinct visitor_id) from page_views),
    'visitor_location', coalesce((select jsonb_build_object('country', country, 'region', region, 'city', city) from visitor_location), '{}'::jsonb),
    'regions', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from region_summary), '[]'::jsonb),
    'devices', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from device_summary), '[]'::jsonb),
    'systems', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from os_summary), '[]'::jsonb),
    'browsers', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from browser_summary), '[]'::jsonb),
    'bots', coalesce((select jsonb_agg(jsonb_build_object('label', label, 'count', total) order by total desc, label asc) from bot_summary), '[]'::jsonb),
    'easter_egg_unique_visitors', (select count(*) from public.visitor_easter_egg_discoveries),
    'generated_at', now()
  ) as payload
  where not (select has_rollup from rollup_exists)
)
select coalesce((select payload from rollup_payload), (select payload from live_payload));
$$;

grant execute on function public.get_visit_analytics_rollup(text) to anon, authenticated;
grant execute on function public.get_visit_analytics_summary(text) to anon, authenticated;

-- Initial refresh. After the updated Edge Function is deployed, new visits refresh this rollup automatically.
select public.refresh_visit_analytics_rollup();
